task/apps/articles/urls.py
from django.http import Http404, HttpResponseRedirect
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
	path('', views.main, name = 'main'),
	path('articles/', views.index, name = 'index'),
	path('authors/', views.authors, name = 'authors'),
	path('articles/<int:article_id>/', views.detail, name = 'detail'),
	path('author/<int:author_id>/', views.author_detail, name = 'author_detail'),
	path('genre/', views.show_genres, name = 'show_genres'),
	path('genre_detail/<int:genre_id>/', views.genre_detail, name = 'genre_detail'),
	path('articles/article_new/', views.article_new, name='article_new'),
	path('articles/<int:article_id>/article_edit/', views.article_edit, name='article_edit'),
	path('articles/author_new/', views.author_new, name='author_new'),
	path('author/<int:author_id>/author_edit/', views.author_edit, name='author_edit'),
	path('articles/genre_new/', views.genre_new, name='genre_new'),
	path('genre_detail/<int:genre_id>/genre_edit/', views.genre_edit, name='genre_edit'),
]

task/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('articles.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

task/apps/articles/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey,TreeManyToManyField


class Author(models.Model):
	author_name = models.CharField('ФИО автора', max_length = 50)
	avatar = models.ImageField('Изображение', null = True, blank = True, upload_to = 'img/')

	def __str__(self):
		return self.author_name


	class Meta:
		verbose_name = 'Автор'
		verbose_name_plural = 'Авторы'


class Genre(MPTTModel):

	class Meta:
		verbose_name = 'Рубрика'
		verbose_name_plural = 'Рубрики'

	name = models.CharField('Рубрика', max_length=50)
	parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children', verbose_name = 'Входит в')
	class MPTTMeta:
		order_insertion_by = ['name']
	def __unicode__(self):
		return self.name
	def __str__(self):
		return self.name



class Article(models.Model):
	article_title = models.CharField('Заголовок', max_length = 100)
	article_announcement = models.CharField('Анонс', max_length = 250)
	article_text = models.TextField('Текст')
	author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
	genre = TreeManyToManyField(Genre, null=True, help_text="Выберите рубрику новости")

	def __str__(self):
		return self.article_title


	class Meta:
		verbose_name = 'Новость'
		verbose_name_plural = 'Новости'

	

task/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from .form import NewArticle, NewAuthor, NewGenre

from .models import Author, Article, Genre

def index(request):
	
	search_query = request.GET.get('search','')

	if search_query:
		articles_list = Article.objects.filter(article_title__icontains = search_query)
	else:
		articles_list = Article.objects.order_by('-id')
	
	return render(request, 'articles/list.html', {'articles_list':articles_list})



def main(request):
	return render(request, 'articles/main.html')

def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id)
	except:
		raise Http404("Нвость отсутствует!")

	return render(request, 'articles/detail.html', {'article':a, 'genres': a.genre.all()})

def author_detail(request, author_id):
	try:
		at = Author.objects.get( id = author_id)
	except:
		raise Http404("Автора нет!")

	return render(request, 'articles/author_detail.html', {'author':at, 'articles': Article.objects.filter(author_id = author_id)})

def show_genres(request):

	search_query = request.GET.get('search','')

	if search_query:
		genre_list = Genre.objects.filter(name__icontains = search_query)
	else:
		genre_list = Genre.objects.all()

	return render(request, "articles/genre.html", {'genres': genre_list})

def genre_detail(request, genre_id):
	try:
		gi = Genre.objects.get( id = genre_id)
	except:
		raise Http404("Рубрика жок!")

	return render(request, 'articles/genre_detail.html', {'node':gi, 'articles': Article.objects.filter(genre = gi)})

def authors(request):
	authors_list = Author.objects.order_by('-id')[:5]
	return render(request, 'articles/authors.html', {'authors_list':authors_list})

def author_new(request):
	if request.method == "POST":
		form = NewAuthor(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			return redirect('articles:author_detail', author_id = post.id)
	else:
		form = NewAuthor()
	return render(request, 'articles/author_new.html', {'form': form})

def author_edit(request, author_id):
    try:
    	post = Author.objects.get( id = author_id)
    except:
    	raise Http404("Автора нет!")
    if request.method == "POST":
        form = NewAuthor(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('articles:author_detail', author_id=post.id)
    else:
        form = NewAuthor(instance=post)
    return render(request, 'articles/author_edit.html', {'form': form})

def article_new(request):
	if request.method == "POST":
		form = NewArticle(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			return redirect('articles:detail', article_id = post.id)
	else:
		form = NewArticle()
	return render(request, 'articles/article_new.html', {'form': form})

def article_edit(request, article_id):
    try:
    	post = Article.objects.get( id = article_id)
    except:
    	raise Http404("Нвость отсутствует!")
    if request.method == "POST":
        form = NewArticle(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('articles:detail', article_id=post.id)
    else:
        form = NewArticle(instance=post)
    return render(request, 'articles/article_edit.html', {'form': form})

def genre_new(request):
	if request.method == "POST":
		form = NewGenre(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			return redirect('articles:genre_detail', genre_id = post.id)
	else:
		form = NewGenre()
	return render(request, 'articles/genre_new.html', {'form': form})

def genre_edit(request, genre_id):
    try:
    	post = Genre.objects.get( id = genre_id)
    except:
    	raise Http404("Рубрика жок!")
    if request.method == "POST":
        form = NewGenre(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('articles:genre_detail', genre_id=post.id)
    else:
        form = NewGenre(instance=post)
    return render(request, 'articles/genre_edit.html', {'form': form})

task/apps/articles/templates/articles/article_edit.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Изменить новость {% endblock %}

{% block content %}  

    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Изменить</button>
    </form>
{% endblock %}

task/apps/articles/templates/articles/article_new.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Добавить новость {% endblock %}

{% block content %}  

    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Добавить</button>
    </form>
{% endblock %}

task/apps/articles/templates/articles/author_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{author.author_name}} {% endblock %}

{% block content %}  

	<div class="row">
		<div class="col-md-5">
			<h2>{{author.author_name}}</h2>
		</div>
		<div class="col-md-7">
			<a class="btn btn-default" href="{% url 'articles:author_edit' author_id=author.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
		</div>
	</div>
	
	{% if author.avatar %}
   		<img src="{{MEDIA_URL}}{{author.avatar.url}}">
    {% else %}
    	<p>Аватар отсутствует ):</p>
    {% endif %}
    <p>Все <a href="{% url 'articles:authors'%}">авторы</a></p>

    {% if articles %}
    	<h4>Новости данной рубрики:</h4>	
		<ul>
			{% for a in articles %}

				<li><h4><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h4></li>

			{% endfor%}
		</ul>
	{% else %}
		<h2>Этот автор не выкладывал новостей -_-</h2>
	{%endif%}
{% endblock %}

task/apps/articles/templates/articles/author_edit.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Изменить автора {% endblock %}

{% block content %}  

    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Изменить</button>
    </form>
{% endblock %}

task/apps/articles/templates/articles/author_new.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Добавить автора {% endblock %}

{% block content %}  

    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Добавить</button>
    </form>
{% endblock %}

task/apps/articles/templates/articles/authors.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Список авторов {% endblock %}

{% block content %}  
	{% if authors_list %}

		{% for a in authors_list %}

			<h4><a href="{% url 'articles:author_detail' a.id %}">{{a.author_name}}</a></h4></br>

		{% endfor%}

	{% else %}
		<h2>Авторы осутствуют</h2>
	{%endif%}
{% endblock %}

task/apps/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} {{article.article_title}} {% endblock %}

{% block content %}  
	<div class="row">
		<div class="col-md-5">
			<h1>{{article.article_title}}</h1>
		</div>
		<div class="col-md-7">
			<a class="btn btn-default" href="{% url 'articles:article_edit' article_id=article.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
		</div>
	</div>
	<br/>
	<h4>Анонс: {{article.article_announcement}}</h4>
	<p>{{article.article_text}}</p>

	<em>Автор: <a href="{% url 'articles:author_detail' article.author.id %}">{{article.author}}</a></em>

	<hr/>
	<h4>Рубрики:</h4>
	<ul>
		{% for node in genres %}
			<li><a href="{% url 'articles:genre_detail' node.id %}">{{ node.name }}</a></li>   
		{% endfor %}
	</ul>

{% endblock %}

task/apps/articles/templates/articles/genre.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Список рубрик {% endblock %}

{% block content %}  
    <form action="{% url 'articles:show_genres' %}">
        <input type="search" placeholder="Поиск рубрики" name="search">
        <button class="btn" type="submit">Поиск</button>
    </form>
    {% if genres %}
    <ul>
        {% recursetree genres %}
            <li>
                <a href="{% url 'articles:genre_detail' node.id %}">{{ node.name }}
                {% if not node.is_leaf_node %}
                    <ul class="children">
                        {{ children }}
                    </ul>
                {% endif %}
                </a>
            </li>
        {% endrecursetree %}
    </ul>
    {% else %}
        <h2>Рубрик нет -_-</h2>
    {%endif%}
{% endblock %}

task/apps/articles/templates/articles/genre_detail.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} {{node.name}} {% endblock %}

{% block content %}  

	<div class="row">
		<div class="col-md-5">
			<h1>Рубрика: {{node.name}}</h1>
		</div>
		<div class="col-md-7">
			<a class="btn btn-default" href="{% url 'articles:genre_edit' genre_id=node.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
		</div>
	</div>
    
    {% if node.parent %}
        <p> Входит в рубрику: <a href="{% url 'articles:genre_detail' node.parent.id %}">{{node.parent}}</a></p>
    {% else %}
        <p> Не входит в какие либо рубрики</p>
    {% endif %}
	<p>Вернуться в <a href="{% url 'articles:show_genres'%}">рубрики</a></p>
    {% if articles %}
    	<h4>Новости данной рубрики:</h4>	
		<ul>
			{% for a in articles %}

				<li><h4><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h4></li>

			{% endfor%}
		</ul>
	{% else %}
		<h2>В данной рубрике новостей нет -_-</h2>
	{%endif%}
{% endblock %}

task/apps/articles/templates/articles/genre_edit.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Изменить рубрику {% endblock %}

{% block content %}  

    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Изменить</button>
    </form>
{% endblock %}

task/apps/articles/templates/articles/genre_new.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Добавить рубрику {% endblock %}

{% block content %}  

    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Добавить</button>
    </form>
{% endblock %}

task/apps/articles/templates/articles/list.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %} Список новостей {% endblock %}

{% block content %}  
	{% if articles_list %}
		<form action="{% url 'articles:index' %}">
		    <input type="search" placeholder="Поиск по названию" name="search">
		    <button class="btn" type="submit">Поиск</button>
		</form>
		{% for a in articles_list %}

			<h4><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h4></br>

		{% endfor%}

	{% else %}
		<h2>Новостей нет -_-</h2>
	{%endif%}
{% endblock %}

task/apps/articles/templates/articles/main.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Главная страница {% endblock %}

{% block content %}  
	<div class="row">
		<div class="col-md-4">
			<h1><a href="{% url 'articles:index' %}">Новости</a></h1>
		</div>
		<div class="col-md-8">
			<a href="{% url 'articles:article_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
		</div>
	</div>
	<hr/>
	<div class="row">
		<div class="col-md-4">
			<h1><a href="{% url 'articles:show_genres' %}">Рубрики</a></h1>
		</div>
		<div class="col-md-8">
			<a href="{% url 'articles:genre_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
		</div>
	</div>
	<hr/>	
	<div class="row">
		<div class="col-md-4">
			<h1><a href="{% url 'articles:authors' %}">Авторы</a></h1>
		</div>
		<div class="col-md-8">
			<a href="{% url 'articles:author_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
		</div>
	</div>
{% endblock %}

task/apps/articles/templates/base.html
{% load static %}
{% load mptt_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} TITULLL {% endblock %}</title>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<body>
	<div class="container">
		<nav class="navbar-collapse">
			<div class="page-header">
		        <h1><a href="{% url 'articles:main' %}">Главная</a></h1>
		    </div>
		    
	    </nav>
	 
		{% block content %}
		{% endblock %}

	</div>
</body>
</html>